services:
  postgres:
    image: postgres:15
    container_name: catalogo-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: catalogo_user
      POSTGRES_PASSWORD: catalogo_pass
      POSTGRES_DB: catalogo_produtos

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
